# Generated by Django 5.1.3 on 2025-03-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_about_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('superadmin', 'Владыка')], default='admin', max_length=10),
        ),
    ]
