# Generated by Django 5.1.3 on 2025-03-11 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_en', models.CharField(max_length=100)),
                ('word_ru', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='word_images/')),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordcards', to='flashcards.flashcard')),
            ],
        ),
    ]
