# Generated by Django 5.1.3 on 2025-03-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhrasalVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100, verbose_name='Глагол')),
                ('particle', models.CharField(max_length=50, verbose_name='Добавление (in/out/etc)')),
                ('translation', models.CharField(max_length=255, verbose_name='Перевод')),
                ('example', models.TextField(verbose_name='Пример использования')),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Learn',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
